/*
 * The MIT License
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package com.sonyericsson.hudson.plugins.gerrit.trigger.coordination.hazelcast;

/**
 * Represents a claimed Gerrit event in the distributed cluster.
 * <p>
 * In HA/HS environments with multiple replicas, each Gerrit event
 * arrives at all replicas. To prevent duplicate builds, replicas use event claiming:
 * the first replica to claim an event processes it, while others skip it.
 * <p>
 * EventClaim objects are stored in a Hazelcast IMap to coordinate claims across replicas.
 * Claims automatically expire via TTL to prevent memory leaks.
 * <p>
 * <strong>Serialization:</strong> Uses Hazelcast Compact Serialization for cross-JVM
 * compatibility with sidecar deployment. The sidecar Hazelcast cluster doesn't need
 * this class in its classpath.
 *
 * @author CloudBees, Inc.
 */
public class EventClaim {

    /**
     * Unique event identifier (generated by {@link EventIdentifier}).
     */
    private final String eventId;

    /**
     * Jenkins instance (hostname/pod name) that claimed the event.
     */
    private final String claimedBy;

    /**
     * Timestamp when event was claimed (milliseconds since epoch).
     */
    private final long claimedAt;

    /**
     * Event type for logging and debugging (e.g., "patchset-created").
     */
    private final String eventType;

    /**
     * Standard constructor.
     *
     * @param eventId unique event identifier
     * @param claimedBy instance that claimed the event
     * @param claimedAt timestamp when claimed
     * @param eventType Gerrit event type
     */
    public EventClaim(String eventId, String claimedBy, long claimedAt, String eventType) {
        this.eventId = eventId;
        this.claimedBy = claimedBy;
        this.claimedAt = claimedAt;
        this.eventType = eventType;
    }

    /**
     * Gets the unique event identifier.
     *
     * @return event ID
     */
    public String getEventId() {
        return eventId;
    }

    /**
     * Gets the instance that claimed the event.
     *
     * @return claimant instance identifier
     */
    public String getClaimedBy() {
        return claimedBy;
    }

    /**
     * Gets the timestamp when the event was claimed.
     *
     * @return claim timestamp (milliseconds since epoch)
     */
    public long getClaimedAt() {
        return claimedAt;
    }

    /**
     * Gets the Gerrit event type.
     *
     * @return event type
     */
    public String getEventType() {
        return eventType;
    }

    @Override
    public String toString() {
        return String.format("EventClaim[id=%s, by=%s, at=%d, type=%s]",
                eventId, claimedBy, claimedAt, eventType);
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        EventClaim that = (EventClaim)o;
        if (eventId != null) {
            return eventId.equals(that.eventId);
        } else {
            return that.eventId == null;
        }
    }

    @Override
    public int hashCode() {
        if (eventId != null) {
            return eventId.hashCode();
        } else {
            return 0;
        }
    }
}
